/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedConversationRouteImport } from './routes/_authenticated/conversation'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGrammarRouteImport } from './routes/_authenticated/grammar'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedListeningRouteImport } from './routes/_authenticated/listening'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedReadingRouteImport } from './routes/_authenticated/reading'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedSpeakingRouteImport } from './routes/_authenticated/speaking'
import { Route as AuthenticatedTranslateRouteImport } from './routes/_authenticated/translate'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedVocabularyRouteImport } from './routes/_authenticated/vocabulary'
import { Route as AuthenticatedWritingRouteImport } from './routes/_authenticated/writing'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn/index'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationRoute =
  AuthenticatedConversationRouteImport.update({
    id: '/conversation',
    path: '/conversation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrammarRoute = AuthenticatedGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListeningRoute = AuthenticatedListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadingRoute = AuthenticatedReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpeakingRoute = AuthenticatedSpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTranslateRoute = AuthenticatedTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabularyRoute = AuthenticatedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWritingRoute = AuthenticatedWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/conversation': typeof AuthenticatedConversationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grammar': typeof AuthenticatedGrammarRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reading': typeof AuthenticatedReadingRoute
  '/review': typeof AuthenticatedReviewRoute
  '/speaking': typeof AuthenticatedSpeakingRoute
  '/translate': typeof AuthenticatedTranslateRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/writing': typeof AuthenticatedWritingRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/conversation': typeof AuthenticatedConversationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grammar': typeof AuthenticatedGrammarRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reading': typeof AuthenticatedReadingRoute
  '/review': typeof AuthenticatedReviewRoute
  '/speaking': typeof AuthenticatedSpeakingRoute
  '/translate': typeof AuthenticatedTranslateRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/writing': typeof AuthenticatedWritingRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/conversation': typeof AuthenticatedConversationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grammar': typeof AuthenticatedGrammarRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/listening': typeof AuthenticatedListeningRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/reading': typeof AuthenticatedReadingRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/speaking': typeof AuthenticatedSpeakingRoute
  '/_authenticated/translate': typeof AuthenticatedTranslateRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/vocabulary': typeof AuthenticatedVocabularyRoute
  '/_authenticated/writing': typeof AuthenticatedWritingRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/conversation'
    | '/dashboard'
    | '/grammar'
    | '/library'
    | '/listening'
    | '/onboarding'
    | '/reading'
    | '/review'
    | '/speaking'
    | '/translate'
    | '/tutor'
    | '/vocabulary'
    | '/writing'
    | '/learn/$slug'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/conversation'
    | '/dashboard'
    | '/grammar'
    | '/library'
    | '/listening'
    | '/onboarding'
    | '/reading'
    | '/review'
    | '/speaking'
    | '/translate'
    | '/tutor'
    | '/vocabulary'
    | '/writing'
    | '/learn/$slug'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/conversation'
    | '/_authenticated/dashboard'
    | '/_authenticated/grammar'
    | '/_authenticated/library'
    | '/_authenticated/listening'
    | '/_authenticated/onboarding'
    | '/_authenticated/reading'
    | '/_authenticated/review'
    | '/_authenticated/speaking'
    | '/_authenticated/translate'
    | '/_authenticated/tutor'
    | '/_authenticated/vocabulary'
    | '/_authenticated/writing'
    | '/_authenticated/learn/$slug'
    | '/_authenticated/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversation': {
      id: '/_authenticated/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof AuthenticatedConversationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grammar': {
      id: '/_authenticated/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof AuthenticatedGrammarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listening': {
      id: '/_authenticated/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AuthenticatedListeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reading': {
      id: '/_authenticated/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof AuthenticatedReadingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speaking': {
      id: '/_authenticated/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof AuthenticatedSpeakingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/translate': {
      id: '/_authenticated/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof AuthenticatedTranslateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocabulary': {
      id: '/_authenticated/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthenticatedVocabularyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/writing': {
      id: '/_authenticated/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof AuthenticatedWritingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedConversationRoute: typeof AuthenticatedConversationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGrammarRoute: typeof AuthenticatedGrammarRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedListeningRoute: typeof AuthenticatedListeningRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedReadingRoute: typeof AuthenticatedReadingRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSpeakingRoute: typeof AuthenticatedSpeakingRoute
  AuthenticatedTranslateRoute: typeof AuthenticatedTranslateRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedVocabularyRoute: typeof AuthenticatedVocabularyRoute
  AuthenticatedWritingRoute: typeof AuthenticatedWritingRoute
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedConversationRoute: AuthenticatedConversationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGrammarRoute: AuthenticatedGrammarRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedListeningRoute: AuthenticatedListeningRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedReadingRoute: AuthenticatedReadingRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSpeakingRoute: AuthenticatedSpeakingRoute,
  AuthenticatedTranslateRoute: AuthenticatedTranslateRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedVocabularyRoute: AuthenticatedVocabularyRoute,
  AuthenticatedWritingRoute: AuthenticatedWritingRoute,
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
