
INSERT INTO public.courses (level_code, title, subtitle, description, sort_order) VALUES
('A0','Absolute Beginner','Mulai dari nol','Alphabet, sounds, greetings and your first English sentences.',0),
('A1','Beginner','Kalimat sehari-hari','Present simple, daily routines, food, shopping and directions.',1),
('A2','Elementary','Cerita & waktu','Past, future, comparatives, travel, health and social situations.',2),
('B1','Intermediate','Ide yang lebih kompleks','Perfect tenses, conditionals, opinions and workplace English.',3),
('B2','Upper Intermediate','Bicara dengan nuansa','Advanced grammar, idioms, debate and professional communication.',4),
('C1','Advanced','Bahasa yang halus','Academic vocabulary, professional writing, nuance and register.',5),
('C2','Mastery','Setara penutur asli','Native-like comprehension, idiomatic language and complex discussion.',6);

INSERT INTO public.modules (course_id, title, description, icon, sort_order)
SELECT c.id, m.title, m.description, m.icon, m.sort_order FROM public.courses c JOIN (VALUES
 ('A0','First Sounds','Alphabet dan bunyi dasar bahasa Inggris.','Type',0),
 ('A0','Hello & You','Menyapa dan memperkenalkan diri.','Hand',1),
 ('A0','Numbers & Colors','Angka, warna, dan benda di sekitarmu.','Palette',2),
 ('A0','First Sentences','Kata ganti, kata kerja dasar, kalimat pertama.','PenLine',3),
 ('A1','Daily Life','Present simple dan rutinitas harian.','Sun',0),
 ('A1','Food & Shopping','Memesan makanan dan berbelanja.','ShoppingBag',1),
 ('A1','Getting Around','Arah, transportasi, dan tempat.','Map',2),
 ('A2','Talking About the Past','Past simple dan bercerita.','History',0),
 ('A2','Plans & Travel','Future forms, travel and health.','Plane',1),
 ('B1','Expressing Yourself','Present perfect, conditionals and opinions.','Sparkles',0),
 ('B1','Workplace English','Meetings, emails and professional talk.','Briefcase',1),
 ('B2','Nuance & Debate','Idioms, argumentation and presentations.','Mic',0),
 ('C1','Register & Precision','Formal vs informal, academic vocabulary.','GraduationCap',0),
 ('C2','Native-like Mastery','Idiomatic language and complex discussion.','Crown',0)
) AS m(level_code,title,description,icon,sort_order) ON m.level_code = c.level_code;

INSERT INTO public.lessons (module_id, slug, title, objective, objective_id, skill, level_code, estimated_minutes, xp_reward, teach, sort_order)
SELECT mo.id, l.slug, l.title, l.objective, l.objective_id, l.skill, l.level_code, l.minutes, l.xp, l.teach::jsonb, l.sort_order
FROM public.modules mo
JOIN public.courses c ON c.id = mo.course_id
JOIN (VALUES
 ('A0','First Sounds','a0-alphabet','The English Alphabet','You will recognise and say all 26 English letters.','Kamu akan mengenal dan menyebut 26 huruf bahasa Inggris.','pronunciation','A0',5,20,
  '[{"en":"A B C D E F G","id":"Ucapkan: ei, bi, si, di, i, ef, ji","note":"Huruf vokal: A E I O U"},{"en":"H I J K L M N","id":"eic, ai, jei, kei, el, em, en"},{"en":"O P Q R S T U V W X Y Z","id":"ou, pi, kiu, ar, es, ti, yu, vi, dabelyu, eks, wai, zi"}]',0),
 ('A0','First Sounds','a0-basic-sounds','Basic Sounds: TH, R, L','You will practise three sounds that are hard for Indonesian speakers.','Kamu akan melatih tiga bunyi yang sulit bagi penutur Indonesia.','pronunciation','A0',6,20,
  '[{"en":"think, three, thank","id":"Bunyi TH: lidah di antara gigi","note":"Bukan \"tink\" atau \"sink\"."},{"en":"red, right, run","id":"Bunyi R: lidah tidak bergetar"},{"en":"light, hello, little","id":"Bunyi L: ujung lidah menyentuh langit-langit"}]',1),
 ('A0','Hello & You','a0-greetings','Greetings','You will greet people at any time of day.','Kamu akan bisa menyapa orang kapan saja.','vocabulary','A0',5,20,
  '[{"en":"Hello / Hi","id":"Halo / Hai"},{"en":"Good morning","id":"Selamat pagi"},{"en":"Good afternoon","id":"Selamat siang"},{"en":"Good evening","id":"Selamat malam"},{"en":"How are you?","id":"Apa kabar?"},{"en":"I am fine, thank you.","id":"Saya baik, terima kasih."}]',0),
 ('A0','Hello & You','a0-introduce','Introducing Yourself','You will introduce yourself naturally in English.','Kamu akan memperkenalkan diri dengan alami.','speaking','A0',7,25,
  '[{"en":"My name is Alex.","id":"Nama saya Alex."},{"en":"I am from Indonesia.","id":"Saya dari Indonesia."},{"en":"I am 20 years old.","id":"Saya berumur 20 tahun."},{"en":"Nice to meet you.","id":"Senang bertemu denganmu."}]',1),
 ('A0','Numbers & Colors','a0-numbers','Numbers 1-20','You will count and say numbers in English.','Kamu akan menghitung dalam bahasa Inggris.','vocabulary','A0',5,20,
  '[{"en":"one, two, three, four, five","id":"satu, dua, tiga, empat, lima"},{"en":"six, seven, eight, nine, ten","id":"enam, tujuh, delapan, sembilan, sepuluh"},{"en":"eleven, twelve, thirteen ... twenty","id":"sebelas, dua belas, tiga belas ... dua puluh"}]',0),
 ('A0','Numbers & Colors','a0-colors','Colors & Objects','You will name colors and everyday objects.','Kamu akan menyebut warna dan benda sehari-hari.','vocabulary','A0',5,20,
  '[{"en":"red, blue, green, yellow, black, white","id":"merah, biru, hijau, kuning, hitam, putih"},{"en":"a book, a chair, a table, a phone","id":"buku, kursi, meja, telepon"},{"en":"This is a red book.","id":"Ini buku merah."}]',1),
 ('A0','First Sentences','a0-pronouns','Pronouns & To Be','You will use I, you, he, she with am/is/are.','Kamu akan memakai I, you, he, she dengan am/is/are.','grammar','A0',7,25,
  '[{"en":"I am a student.","id":"Saya seorang murid."},{"en":"You are my friend.","id":"Kamu temanku."},{"en":"He is a teacher. She is a doctor.","id":"Dia guru. Dia dokter."},{"en":"We are happy. They are here.","id":"Kami senang. Mereka di sini."}]',0),
 ('A0','First Sentences','a0-first-sentences','Your First Sentences','You will build simple subject + verb + object sentences.','Kamu akan menyusun kalimat sederhana.','writing','A0',7,25,
  '[{"en":"I drink water.","id":"Saya minum air."},{"en":"She reads a book.","id":"Dia membaca buku."},{"en":"Subject + Verb + Object","id":"Subjek + Kata kerja + Objek","note":"Urutan ini hampir selalu tetap dalam bahasa Inggris."}]',1),
 ('A1','Daily Life','a1-present-simple','Present Simple','You will talk about habits and routines.','Kamu akan berbicara tentang kebiasaan.','grammar','A1',8,30,
  '[{"en":"I work every day.","id":"Saya bekerja setiap hari."},{"en":"She likes coffee.","id":"Dia suka kopi.","note":"he/she/it + s"},{"en":"They do not study on Sunday.","id":"Mereka tidak belajar hari Minggu."},{"en":"Do you speak English?","id":"Apakah kamu bisa bahasa Inggris?"}]',0),
 ('A1','Daily Life','a1-routines','My Daily Routine','You will describe your day from morning to night.','Kamu akan menceritakan harimu.','speaking','A1',8,30,
  '[{"en":"I wake up at six.","id":"Saya bangun jam enam."},{"en":"I have breakfast, then I go to work.","id":"Saya sarapan, lalu pergi bekerja."},{"en":"In the evening I watch TV.","id":"Malam hari saya menonton TV."}]',1),
 ('A1','Food & Shopping','a1-ordering-food','Ordering Food','You will order food and drinks in a cafe.','Kamu akan memesan makanan di kafe.','speaking','A1',8,30,
  '[{"en":"Can I have a coffee, please?","id":"Boleh saya pesan kopi?"},{"en":"I would like the chicken rice.","id":"Saya mau nasi ayam."},{"en":"How much is it?","id":"Berapa harganya?"},{"en":"Anything else? - No, that is all.","id":"Ada lagi? - Tidak, itu saja."}]',0),
 ('A1','Food & Shopping','a1-shopping','Shopping','You will buy things and ask about price and size.','Kamu akan berbelanja dan menanyakan harga.','vocabulary','A1',7,25,
  '[{"en":"Do you have this in medium?","id":"Ada ukuran medium?"},{"en":"It is too expensive.","id":"Terlalu mahal."},{"en":"Can I pay by card?","id":"Bisa bayar pakai kartu?"}]',1),
 ('A1','Getting Around','a1-directions','Asking for Directions','You will ask for and understand directions.','Kamu akan menanyakan arah.','listening','A1',8,30,
  '[{"en":"Excuse me, where is the station?","id":"Permisi, di mana stasiunnya?"},{"en":"Go straight, then turn left.","id":"Jalan lurus, lalu belok kiri."},{"en":"It is next to the bank.","id":"Letaknya di sebelah bank."}]',0),
 ('A1','Getting Around','a1-transport','Transportation','You will talk about how you travel every day.','Kamu akan bicara tentang transportasi.','vocabulary','A1',6,25,
  '[{"en":"I go to work by bus.","id":"Saya pergi kerja naik bus."},{"en":"train, taxi, motorbike, plane","id":"kereta, taksi, motor, pesawat"}]',1),
 ('A2','Talking About the Past','a2-past-simple','Past Simple','You will talk about finished actions in the past.','Kamu akan bercerita tentang masa lalu.','grammar','A2',9,35,
  '[{"en":"I went to school yesterday.","id":"Saya pergi ke sekolah kemarin.","note":"go -> went (irregular)"},{"en":"She watched a movie last night.","id":"Dia menonton film tadi malam."},{"en":"Did you eat?  I did not eat.","id":"Apakah kamu makan? Saya tidak makan."}]',0),
 ('A2','Talking About the Past','a2-storytelling','Telling a Short Story','You will connect events with first, then, after that.','Kamu akan merangkai cerita pendek.','writing','A2',9,35,
  '[{"en":"First, I woke up late.","id":"Pertama, saya bangun kesiangan."},{"en":"Then I missed the bus.","id":"Lalu saya ketinggalan bus."},{"en":"In the end, I arrived on time.","id":"Akhirnya saya tiba tepat waktu."}]',1),
 ('A2','Plans & Travel','a2-future','Talking About the Future','You will use will and going to for plans.','Kamu akan bicara tentang rencana.','grammar','A2',8,35,
  '[{"en":"I am going to visit Bali next month.","id":"Saya akan mengunjungi Bali bulan depan.","note":"rencana yang sudah pasti"},{"en":"I think it will rain.","id":"Saya rasa akan hujan.","note":"prediksi"}]',0),
 ('A2','Plans & Travel','a2-airport','At the Airport','You will handle check-in and airport questions.','Kamu akan menghadapi situasi bandara.','listening','A2',8,35,
  '[{"en":"May I see your passport?","id":"Boleh lihat paspor Anda?"},{"en":"Do you have any luggage to check in?","id":"Ada bagasi yang mau dititipkan?"},{"en":"Boarding starts at gate 12.","id":"Boarding di gerbang 12."}]',1),
 ('B1','Expressing Yourself','b1-present-perfect','Present Perfect','You will link the past to now.','Kamu akan menghubungkan masa lalu dengan sekarang.','grammar','B1',10,40,
  '[{"en":"I have lived here for five years.","id":"Saya sudah tinggal di sini lima tahun."},{"en":"Have you ever tried sushi?","id":"Pernahkah kamu mencoba sushi?"},{"en":"She has just finished her work.","id":"Dia baru saja menyelesaikan pekerjaannya."}]',0),
 ('B1','Expressing Yourself','b1-opinions','Giving Opinions','You will express and support an opinion politely.','Kamu akan menyampaikan pendapat.','speaking','B1',10,40,
  '[{"en":"In my opinion, remote work is better.","id":"Menurut saya, kerja jarak jauh lebih baik."},{"en":"I see your point, but ...","id":"Saya paham maksudmu, tapi ..."},{"en":"The main reason is that ...","id":"Alasan utamanya adalah ..."}]',1),
 ('B1','Workplace English','b1-meetings','Meetings & Emails','You will speak up in meetings and write clear emails.','Kamu akan aktif di rapat dan menulis email.','writing','B1',10,40,
  '[{"en":"Could we go over the timeline?","id":"Bisakah kita bahas jadwalnya?"},{"en":"I would like to follow up on my last email.","id":"Saya ingin menindaklanjuti email saya."},{"en":"Please let me know if you have any questions.","id":"Beri tahu saya jika ada pertanyaan."}]',0)
) AS l(level_code,module_title,slug,title,objective,objective_id,skill,lvl,minutes,xp,teach,sort_order)
  ON l.module_title = mo.title AND l.level_code = c.level_code;

INSERT INTO public.exercises (lesson_id, kind, prompt, prompt_id, options, answer, explanation, audio_text, sort_order)
SELECT le.id, e.kind, e.prompt, e.prompt_id, e.options::jsonb, e.answer, e.explanation, e.audio_text, e.sort_order
FROM public.lessons le JOIN (VALUES
 ('a0-alphabet','multiple_choice','Which letter comes after D?','Huruf apa setelah D?','["C","E","F","G"]','E','A B C D E — E langsung setelah D.',NULL,0),
 ('a0-alphabet','multiple_choice','How many vowels are in the English alphabet (a, e, i, o, u)?','Ada berapa huruf vokal?','["3","4","5","6"]','5','A, E, I, O, U = 5 huruf vokal.',NULL,1),
 ('a0-alphabet','listening','Type the letter you hear.','Ketik huruf yang kamu dengar.','[]','Z','Z diucapkan "zi" (US) atau "zed" (UK).','Z',2),
 ('a0-basic-sounds','multiple_choice','Which word has the TH sound?','Kata mana yang punya bunyi TH?','["tree","three","free","see"]','three','"Three" memakai TH: lidah di antara gigi.',NULL,0),
 ('a0-basic-sounds','listening','Type the word you hear.','Ketik kata yang kamu dengar.','[]','light','L di awal: ujung lidah menyentuh langit-langit.','light',1),
 ('a0-greetings','multiple_choice','It is 8 in the morning. What do you say?','Jam 8 pagi, kamu bilang apa?','["Good night","Good morning","Good evening","Goodbye"]','Good morning','Pagi hari = Good morning (sampai jam 12 siang).',NULL,0),
 ('a0-greetings','fill_blank','How ___ you?','Apa kabar? Lengkapi kalimatnya.','[]','are','"How are you?" — dengan you kita memakai "are".',NULL,1),
 ('a0-greetings','translate','Translate: Selamat malam.','Terjemahkan ke bahasa Inggris.','[]','Good evening','"Good evening" untuk menyapa di malam hari.',NULL,2),
 ('a0-introduce','sentence_order','Build the sentence.','Susun kalimatnya.','["My","name","is","Alex"]','My name is Alex','Subjek dulu, lalu kata kerja "is".',NULL,0),
 ('a0-introduce','fill_blank','I ___ from Indonesia.','Lengkapi kalimatnya.','[]','am','Dengan "I" selalu memakai "am".',NULL,1),
 ('a0-introduce','speaking','Say: Hello, my name is ... Nice to meet you.','Ucapkan perkenalan dirimu.','[]','Hello my name is','Latih intonasi ramah dan jeda setelah nama.',NULL,2),
 ('a0-numbers','multiple_choice','What is "twelve" in numbers?','Berapa "twelve"?','["2","12","20","22"]','12','twelve = 12, twenty = 20.',NULL,0),
 ('a0-numbers','listening','Type the number you hear.','Ketik angka yang kamu dengar.','[]','seven','seven = tujuh.','seven',1),
 ('a0-colors','matching','What color is the sky on a clear day?','Apa warna langit cerah?','["red","blue","green","black"]','blue','sky = langit, blue = biru.',NULL,0),
 ('a0-colors','sentence_order','Build the sentence.','Susun kalimatnya.','["This","is","a","red","book"]','This is a red book','Dalam bahasa Inggris warna berada sebelum benda.',NULL,1),
 ('a0-pronouns','multiple_choice','She ___ a doctor.','Pilih kata yang tepat.','["am","is","are","be"]','is','he / she / it selalu memakai "is".',NULL,0),
 ('a0-pronouns','fill_blank','They ___ my friends.','Lengkapi kalimatnya.','[]','are','we / you / they memakai "are".',NULL,1),
 ('a0-pronouns','true_false','"I are happy" is correct English.','Benar atau salah?','["True","False"]','False','Yang benar: "I am happy".',NULL,2),
 ('a0-first-sentences','sentence_order','Build the sentence.','Susun kalimatnya.','["I","drink","water","every","day"]','I drink water every day','Subjek + kata kerja + objek + keterangan waktu.',NULL,0),
 ('a0-first-sentences','translate','Translate: Dia membaca buku.','Terjemahkan (dia = perempuan).','[]','She reads a book','Untuk she, kata kerja mendapat -s: read -> reads.',NULL,1),
 ('a1-present-simple','multiple_choice','He ___ coffee every morning.','Pilih kata yang tepat.','["drink","drinks","drinking","drank"]','drinks','he/she/it + kata kerja + s.',NULL,0),
 ('a1-present-simple','fill_blank','___ you speak English?','Lengkapi pertanyaannya.','[]','Do','Pertanyaan present simple dengan you memakai "Do".',NULL,1),
 ('a1-present-simple','sentence_order','Build the sentence.','Susun kalimatnya.','["She","does","not","like","tea"]','She does not like tea','Negatif untuk she: does not + kata kerja dasar.',NULL,2),
 ('a1-routines','translate','Translate: Saya bangun jam enam.','Terjemahkan.','[]','I wake up at six','"at" dipakai untuk jam tertentu.',NULL,0),
 ('a1-routines','speaking','Describe your morning in three sentences.','Ceritakan pagimu dalam tiga kalimat.','[]','I wake up','Gunakan present simple: I wake up, I have, I go.',NULL,1),
 ('a1-ordering-food','multiple_choice','Which is the most polite?','Mana yang paling sopan?','["Give me coffee.","Coffee!","Can I have a coffee, please?","I want coffee now."]','Can I have a coffee, please?','"Can I have ..., please?" adalah cara sopan memesan.',NULL,0),
 ('a1-ordering-food','listening','Type what the waiter asks.','Ketik pertanyaan pelayan.','[]','Anything else','Pelayan sering bertanya "Anything else?"','Anything else',1),
 ('a1-shopping','fill_blank','How ___ is this shirt?','Lengkapi kalimatnya.','[]','much','Untuk harga: "How much is ...?"',NULL,0),
 ('a1-directions','listening','Type the missing word: Go straight, then turn ___.','Ketik kata yang hilang.','[]','left','turn left = belok kiri.','Go straight then turn left',0),
 ('a1-directions','multiple_choice','"It is next to the bank" means:','Artinya:','["Di depan bank","Di sebelah bank","Jauh dari bank","Di dalam bank"]','Di sebelah bank','next to = di sebelah.',NULL,1),
 ('a1-transport','translate','Translate: Saya pergi kerja naik bus.','Terjemahkan.','[]','I go to work by bus','Transportasi memakai "by": by bus, by train.',NULL,0),
 ('a2-past-simple','multiple_choice','I ___ to school yesterday.','Pilih kata yang tepat.','["go","goes","went","gone"]','went','go menjadi went di past simple.',NULL,0),
 ('a2-past-simple','fill_blank','She ___ not call me last night.','Lengkapi kalimatnya.','[]','did','Negatif lampau: did not + kata kerja dasar.',NULL,1),
 ('a2-past-simple','sentence_order','Build the sentence.','Susun kalimatnya.','["We","watched","a","movie","last","night"]','We watched a movie last night','Kata kerja beraturan mendapat -ed.',NULL,2),
 ('a2-storytelling','translate','Translate: Lalu saya ketinggalan bus.','Terjemahkan.','[]','Then I missed the bus','miss the bus = ketinggalan bus.',NULL,0),
 ('a2-future','multiple_choice','I already bought tickets. I ___ visit Bali.','Pilih yang paling tepat.','["will","am going to","would","was going"]','am going to','Rencana yang sudah pasti memakai "going to".',NULL,0),
 ('a2-airport','listening','Type the missing word: May I see your ___?','Ketik kata yang hilang.','[]','passport','Petugas meminta paspor saat check-in.','May I see your passport',0),
 ('b1-present-perfect','multiple_choice','I ___ here for five years.','Pilih yang tepat.','["live","lived","have lived","am living"]','have lived','Aksi mulai di masa lalu dan masih berlanjut = present perfect.',NULL,0),
 ('b1-present-perfect','fill_blank','Have you ___ tried sushi?','Lengkapi kalimatnya.','[]','ever','"Have you ever ...?" menanyakan pengalaman.',NULL,1),
 ('b1-opinions','sentence_order','Build the sentence.','Susun kalimatnya.','["In","my","opinion","remote","work","is","better"]','In my opinion remote work is better','Frasa pembuka pendapat diletakkan di awal.',NULL,0),
 ('b1-meetings','multiple_choice','Which is the best email closing?','Mana penutup email terbaik?','["Bye bye","Please let me know if you have any questions.","Answer fast.","Thats all."]','Please let me know if you have any questions.','Penutup profesional dan ramah.',NULL,0)
) AS e(slug,kind,prompt,prompt_id,options,answer,explanation,audio_text,sort_order) ON e.slug = le.slug;

INSERT INTO public.vocabulary (word, ipa, word_type, meaning_id, meaning_en, example, example_id, category, level_code) VALUES
('hello','/həˈloʊ/','interjection','halo','a greeting','Hello, how are you?','Halo, apa kabar?','Daily Life','A0'),
('water','/ˈwɔː.tər/','noun','air','clear drink','I drink water every day.','Saya minum air setiap hari.','Food','A0'),
('rice','/raɪs/','noun','nasi','cooked grain','I eat rice for lunch.','Saya makan nasi saat siang.','Food','A0'),
('friend','/frend/','noun','teman','a person you like','She is my best friend.','Dia sahabat saya.','Daily Life','A0'),
('house','/haʊs/','noun','rumah','a building to live in','My house is small.','Rumah saya kecil.','Daily Life','A0'),
('book','/bʊk/','noun','buku','pages with text','This book is interesting.','Buku ini menarik.','School','A0'),
('teacher','/ˈtiː.tʃər/','noun','guru','a person who teaches','My teacher is kind.','Guru saya baik.','School','A0'),
('red','/red/','adjective','merah','a color','I have a red bag.','Saya punya tas merah.','Daily Life','A0'),
('mother','/ˈmʌð.ər/','noun','ibu','female parent','My mother cooks well.','Ibu saya pandai memasak.','Family','A0'),
('father','/ˈfɑː.ðər/','noun','ayah','male parent','My father works in Jakarta.','Ayah saya bekerja di Jakarta.','Family','A0'),
('morning','/ˈmɔːr.nɪŋ/','noun','pagi','early part of the day','I study in the morning.','Saya belajar di pagi hari.','Daily Life','A0'),
('name','/neɪm/','noun','nama','what you are called','My name is Alex.','Nama saya Alex.','Daily Life','A0'),
('work','/wɜːrk/','verb','bekerja','to do a job','I work every day.','Saya bekerja setiap hari.','Work','A1'),
('beautiful','/ˈbjuː.tɪ.fəl/','adjective','indah','very pretty','She has a beautiful smile.','Dia punya senyum yang indah.','Emotions','A1'),
('expensive','/ɪkˈspen.sɪv/','adjective','mahal','costs a lot','This phone is too expensive.','Ponsel ini terlalu mahal.','Shopping','A1'),
('cheap','/tʃiːp/','adjective','murah','low price','The bus is cheap.','Busnya murah.','Shopping','A1'),
('breakfast','/ˈbrek.fəst/','noun','sarapan','morning meal','I have breakfast at seven.','Saya sarapan jam tujuh.','Food','A1'),
('station','/ˈsteɪ.ʃən/','noun','stasiun','place for trains','The station is near here.','Stasiunnya dekat sini.','Transportation','A1'),
('left','/left/','adverb','kiri','opposite of right','Turn left at the corner.','Belok kiri di sudut.','Transportation','A1'),
('busy','/ˈbɪz.i/','adjective','sibuk','having much to do','I am busy today.','Saya sibuk hari ini.','Work','A1'),
('weather','/ˈweð.ər/','noun','cuaca','sun, rain, wind','The weather is nice today.','Cuacanya bagus hari ini.','Nature','A1'),
('hobby','/ˈhɒb.i/','noun','hobi','free time activity','My hobby is reading.','Hobi saya membaca.','Entertainment','A1'),
('doctor','/ˈdɒk.tər/','noun','dokter','medical person','I need to see a doctor.','Saya perlu ke dokter.','Health','A1'),
('travel','/ˈtræv.əl/','verb','bepergian','to go to places','I love to travel.','Saya suka bepergian.','Travel','A2'),
('luggage','/ˈlʌɡ.ɪdʒ/','noun','bagasi','bags for travel','My luggage is heavy.','Bagasi saya berat.','Travel','A2'),
('yesterday','/ˈjes.tər.deɪ/','adverb','kemarin','the day before today','I went out yesterday.','Saya keluar kemarin.','Daily Life','A2'),
('healthy','/ˈhel.θi/','adjective','sehat','in good health','Walking keeps me healthy.','Berjalan membuat saya sehat.','Health','A2'),
('improve','/ɪmˈpruːv/','verb','meningkatkan','to make better','I want to improve my English.','Saya ingin meningkatkan bahasa Inggris saya.','Daily Life','A2'),
('although','/ɔːlˈðoʊ/','conjunction','meskipun','despite the fact','Although it rained, we went out.','Meskipun hujan, kami keluar.','Daily Life','B1'),
('opinion','/əˈpɪn.jən/','noun','pendapat','what you think','In my opinion, it is fair.','Menurut saya, itu adil.','Business','B1'),
('deadline','/ˈded.laɪn/','noun','tenggat waktu','final time limit','We must meet the deadline.','Kita harus memenuhi tenggat waktu.','Work','B1'),
('experience','/ɪkˈspɪr.i.əns/','noun','pengalaman','what you have done','She has five years of experience.','Dia punya pengalaman lima tahun.','Work','B1'),
('reliable','/rɪˈlaɪ.ə.bəl/','adjective','dapat diandalkan','can be trusted','He is a reliable colleague.','Dia rekan yang dapat diandalkan.','Work','B2'),
('nevertheless','/ˌnev.ə.ðəˈles/','adverb','namun demikian','in spite of that','It was hard; nevertheless, we finished.','Itu sulit; namun demikian kami selesai.','Business','B2'),
('breakthrough','/ˈbreɪk.θruː/','noun','terobosan','important discovery','The team made a breakthrough.','Tim itu membuat terobosan.','Technology','B2'),
('nuance','/ˈnuː.ɑːns/','noun','nuansa','subtle difference','He missed the nuance of the joke.','Dia tak menangkap nuansa leluconnya.','Entertainment','C1'),
('compelling','/kəmˈpel.ɪŋ/','adjective','meyakinkan','very convincing','She made a compelling argument.','Dia membuat argumen yang meyakinkan.','Business','C1'),
('ubiquitous','/juːˈbɪk.wɪ.təs/','adjective','ada di mana-mana','found everywhere','Smartphones are ubiquitous.','Ponsel pintar ada di mana-mana.','Technology','C2');

INSERT INTO public.grammar_topics (slug, title, level_code, summary, summary_id, explanation, examples, exercises, sort_order) VALUES
('to-be','Am / Is / Are','A0','The verb "to be" links a subject to a description.','Kata kerja "to be" menghubungkan subjek dengan keterangan.',
 '["I + am","He / She / It + is","You / We / They + are"]',
 '[{"en":"I am tired.","id":"Saya lelah."},{"en":"She is a nurse.","id":"Dia perawat."},{"en":"They are at home.","id":"Mereka di rumah."}]',
 '[{"prompt":"He ___ my brother.","options":["am","is","are"],"answer":"is","explanation":"he selalu memakai is."},{"prompt":"We ___ ready.","options":["am","is","are"],"answer":"are","explanation":"we memakai are."}]',0),
('present-simple','Present Simple','A1','Use it for habits, routines and facts.','Dipakai untuk kebiasaan, rutinitas, dan fakta.',
 '["Positive: I work / She works","Negative: I do not work / She does not work","Question: Do you work? / Does she work?"]',
 '[{"en":"I work every day.","id":"Saya bekerja setiap hari."},{"en":"She likes coffee.","id":"Dia suka kopi."},{"en":"Water boils at 100 degrees.","id":"Air mendidih pada 100 derajat."}]',
 '[{"prompt":"She ___ (go) to school.","options":["go","goes","going"],"answer":"goes","explanation":"she + kata kerja + es."},{"prompt":"___ they live here?","options":["Do","Does","Is"],"answer":"Do","explanation":"they memakai Do."}]',1),
('present-continuous','Present Continuous','A1','Use it for actions happening right now.','Dipakai untuk aksi yang sedang terjadi sekarang.',
 '["am / is / are + verb-ing"]',
 '[{"en":"I am studying English now.","id":"Saya sedang belajar bahasa Inggris."},{"en":"They are watching TV.","id":"Mereka sedang menonton TV."}]',
 '[{"prompt":"He ___ working right now.","options":["is","are","do"],"answer":"is","explanation":"he + is + verb-ing."}]',2),
('past-simple','Past Simple','A2','Use it for finished actions in the past.','Dipakai untuk aksi yang sudah selesai di masa lalu.',
 '["Regular: work -> worked","Irregular: go -> went, eat -> ate","Negative/Question: did not + base verb / Did you ...?"]',
 '[{"en":"I visited my aunt last week.","id":"Saya mengunjungi bibi minggu lalu."},{"en":"She did not come.","id":"Dia tidak datang."}]',
 '[{"prompt":"They ___ dinner at eight.","options":["have","had","has"],"answer":"had","explanation":"have menjadi had."},{"prompt":"Did you ___ the film?","options":["saw","see","seen"],"answer":"see","explanation":"Setelah did selalu kata kerja dasar."}]',3),
('comparatives','Comparatives & Superlatives','A2','Compare two or more things.','Membandingkan dua hal atau lebih.',
 '["Short words: cheap -> cheaper -> the cheapest","Long words: expensive -> more expensive -> the most expensive","Irregular: good -> better -> the best"]',
 '[{"en":"This bag is cheaper than that one.","id":"Tas ini lebih murah dari yang itu."},{"en":"It is the best restaurant in town.","id":"Ini restoran terbaik di kota."}]',
 '[{"prompt":"My phone is ___ than yours.","options":["new","newer","newest"],"answer":"newer","explanation":"Perbandingan dua benda memakai -er + than."}]',4),
('modals','Modal Verbs','A2','can, must, should, may express ability and advice.','can, must, should, may menyatakan kemampuan dan saran.',
 '["can = bisa","must = harus","should = sebaiknya","may = boleh"]',
 '[{"en":"You should rest.","id":"Sebaiknya kamu istirahat."},{"en":"I can swim.","id":"Saya bisa berenang."}]',
 '[{"prompt":"You ___ see a doctor.","options":["should","can not","may not"],"answer":"should","explanation":"should untuk memberi saran."}]',5),
('present-perfect','Present Perfect','B1','Link a past action to the present.','Menghubungkan aksi lampau dengan sekarang.',
 '["have / has + past participle","for + duration, since + starting point","just, already, yet"]',
 '[{"en":"I have lived here since 2019.","id":"Saya tinggal di sini sejak 2019."},{"en":"He has just left.","id":"Dia baru saja pergi."}]',
 '[{"prompt":"She ___ finished her homework.","options":["have","has","had"],"answer":"has","explanation":"she memakai has."}]',6),
('conditionals','Conditionals','B1','Talk about real and unreal situations.','Membahas situasi nyata dan tidak nyata.',
 '["First: If it rains, I will stay home.","Second: If I had time, I would travel.","Zero: If you heat water, it boils."]',
 '[{"en":"If you study, you will pass.","id":"Jika kamu belajar, kamu akan lulus."},{"en":"If I were you, I would apologise.","id":"Jika saya jadi kamu, saya akan minta maaf."}]',
 '[{"prompt":"If it rains, I ___ stay home.","options":["will","would","was"],"answer":"will","explanation":"First conditional memakai will."}]',7),
('passive','Passive Voice','B1','Focus on the action, not the doer.','Fokus pada aksi, bukan pelakunya.',
 '["be + past participle","The report was written by Maya."]',
 '[{"en":"The email was sent yesterday.","id":"Email itu dikirim kemarin."}]',
 '[{"prompt":"The room ___ cleaned every day.","options":["is","has","does"],"answer":"is","explanation":"Pasif present: is + past participle."}]',8),
('phrasal-verbs','Phrasal Verbs','B2','Verb + particle with a new meaning.','Kata kerja + partikel dengan makna baru.',
 '["look after = merawat","give up = menyerah","put off = menunda","come across = menemukan tanpa sengaja"]',
 '[{"en":"Do not give up now.","id":"Jangan menyerah sekarang."},{"en":"We put off the meeting.","id":"Kami menunda rapat."}]',
 '[{"prompt":"She had to ___ after her sister.","options":["look","give","put"],"answer":"look","explanation":"look after = merawat."}]',9);

INSERT INTO public.listening_exercises (title, level_code, transcript, translation, questions, sort_order) VALUES
('Meeting a New Person','A0','Hi! My name is Sarah. I am from Canada. Nice to meet you.','Hai! Nama saya Sarah. Saya dari Kanada. Senang bertemu denganmu.',
 '[{"prompt":"Where is Sarah from?","options":["Canada","Japan","Brazil"],"answer":"Canada"},{"prompt":"Type the missing word: My ___ is Sarah.","answer":"name"}]',0),
('At the Cafe','A1','Good morning! What can I get you? I would like a small coffee and a sandwich, please. Anything else? No, that is all.','Selamat pagi! Mau pesan apa? Saya mau kopi kecil dan roti lapis. Ada lagi? Tidak, itu saja.',
 '[{"prompt":"What does the customer order?","options":["Tea and cake","Coffee and a sandwich","Juice"],"answer":"Coffee and a sandwich"},{"prompt":"Type the missing word: Anything ___?","answer":"else"}]',1),
('Asking for Directions','A1','Excuse me, where is the train station? Go straight for two blocks, then turn left. It is next to the bank.','Permisi, di mana stasiun kereta? Jalan lurus dua blok, lalu belok kiri. Letaknya di sebelah bank.',
 '[{"prompt":"Which way do you turn?","options":["Right","Left","Back"],"answer":"Left"},{"prompt":"The station is next to the ___.","answer":"bank"}]',2),
('Airport Check-in','A2','May I see your passport, please? Do you have any luggage to check in? Just one bag. Your flight boards at gate twelve.','Boleh lihat paspor Anda? Ada bagasi? Hanya satu tas. Penerbangan Anda boarding di gerbang dua belas.',
 '[{"prompt":"Which gate?","options":["Two","Twelve","Twenty"],"answer":"Twelve"}]',3),
('A Job Interview','B1','So, tell me about your experience. I have worked as a designer for four years, mostly on mobile apps. That sounds great. Why do you want this role?','Ceritakan pengalaman Anda. Saya bekerja sebagai desainer selama empat tahun, kebanyakan aplikasi mobile.',
 '[{"prompt":"How long has the candidate worked?","options":["Two years","Four years","Ten years"],"answer":"Four years"}]',4);

INSERT INTO public.reading_passages (title, level_code, body, glossary, questions, sort_order) VALUES
('My Family','A0','This is my family. My father is a driver. My mother is a teacher. I have one sister. She is ten years old. We live in a small house. We are happy.',
 '[{"word":"father","meaning":"ayah"},{"word":"sister","meaning":"saudara perempuan"},{"word":"house","meaning":"rumah"}]',
 '[{"prompt":"What is the mother''s job?","options":["Driver","Teacher","Doctor"],"answer":"Teacher"},{"prompt":"How old is the sister?","options":["Ten","Twelve","Five"],"answer":"Ten"}]',0),
('A Busy Monday','A1','Rina wakes up at six every morning. She has breakfast with her family and then takes the bus to work. Her office is near the station. On Monday she is very busy, but she likes her job.',
 '[{"word":"busy","meaning":"sibuk"},{"word":"office","meaning":"kantor"},{"word":"near","meaning":"dekat"}]',
 '[{"prompt":"How does Rina go to work?","options":["By car","By bus","On foot"],"answer":"By bus"},{"prompt":"What is the main idea?","options":["Rina''s daily routine","Rina''s holiday","Rina''s family"],"answer":"Rina''s daily routine"}]',1),
('A Trip to Bali','A2','Last year, Dimas travelled to Bali with two friends. They stayed in a small hotel near the beach. Every morning they swam in the sea, and in the evening they tried local food. The trip was cheap but unforgettable.',
 '[{"word":"stayed","meaning":"menginap"},{"word":"unforgettable","meaning":"tak terlupakan"}]',
 '[{"prompt":"When did they swim?","options":["In the morning","At night","At noon"],"answer":"In the morning"},{"prompt":"The trip was ___.","options":["expensive","cheap","boring"],"answer":"cheap"}]',2),
('Working From Home','B1','Remote work has changed how many people live. Employees save hours of commuting and can organise their day more freely. However, some people feel isolated and find it hard to separate work from private life. Most experts agree that a hybrid model works best.',
 '[{"word":"commuting","meaning":"perjalanan ke kantor"},{"word":"isolated","meaning":"terisolasi"},{"word":"hybrid","meaning":"campuran"}]',
 '[{"prompt":"What is the main idea?","options":["Remote work has benefits and drawbacks","Offices are closing","Nobody likes remote work"],"answer":"Remote work has benefits and drawbacks"},{"prompt":"What do experts recommend?","options":["Full office","Full remote","A hybrid model"],"answer":"A hybrid model"}]',3);

INSERT INTO public.writing_prompts (title, level_code, prompt, guidance, min_words, sort_order) VALUES
('About Me','A0','Write 3 sentences about yourself.','Gunakan: My name is ... / I am from ... / I like ...',10,0),
('My Daily Routine','A1','Describe your daily routine from morning to night.','Gunakan present simple dan kata waktu: in the morning, then, after that.',40,1),
('My Last Weekend','A2','Write about what you did last weekend.','Gunakan past simple: went, ate, watched.',60,2),
('A Place I Love','A2','Describe a place you love and explain why.','Gunakan kata sifat dan alasan: because, so.',70,3),
('Social Media Opinion','B1','Write your opinion about social media. Is it good or bad for young people?','Gunakan: In my opinion, On the other hand, In conclusion.',100,4),
('A Professional Email','B1','Write an email to your manager asking for two days off.','Gunakan bahasa sopan: I would like to, Please let me know.',80,5);

INSERT INTO public.conversation_scenarios (slug, title, description, situation, partner_style, difficulty, icon, opener, sort_order) VALUES
('meeting-someone','Meeting Someone New','Small talk with a new acquaintance.','You meet a new person at a language exchange event.','Friendly','A1','Handshake','Hey! Nice to meet you. I''m Jamie. What do you do?',0),
('ordering-food','Ordering Food','Order at a cafe and pay.','You are a customer at a busy cafe. The AI is the waiter.','Casual','A1','UtensilsCrossed','Good morning! Welcome to Bean Street. What can I get for you today?',1),
('at-the-airport','At the Airport','Check in and find your gate.','You are checking in for an international flight.','Professional','A2','Plane','Good afternoon. May I see your passport and booking, please?',2),
('shopping','Shopping for Clothes','Ask about size, colour and price.','You are shopping for a shirt in a clothes store.','Friendly','A1','ShoppingBag','Hi there! Are you looking for anything in particular today?',3),
('job-interview','Job Interview','Answer common interview questions.','You are interviewing for a junior role at a tech company.','Professional','B1','Briefcase','Thanks for coming in. To start, could you tell me a little about yourself?',4),
('talking-to-a-friend','Talking to a Friend','Catch up casually.','You bump into an old friend on the street.','Casual','A2','Coffee','Heyyy! Long time no see! How have you been?',5),
('asking-directions','Asking for Directions','Find your way in a new city.','You are lost and ask a local for help.','Friendly','A1','Map','You look a bit lost — can I help you find something?',6),
('university','University Conversation','Talk with a classmate about study.','You talk to a classmate before a lecture.','Casual','B1','GraduationCap','Hey, did you manage to finish the reading for today''s class?',7),
('workplace','Workplace Conversation','Discuss a task with a colleague.','You discuss a project deadline with a colleague.','Professional','B1','Building2','Morning! Do you have five minutes to go over the project timeline?',8),
('hotel-checkin','Hotel Check-in','Check into a hotel room.','You arrive at a hotel with a reservation.','Professional','A2','BedDouble','Good evening and welcome. Do you have a reservation with us?',9),
('small-talk','Making Small Talk','Weather, weekend and light topics.','You chat with someone while waiting in a queue.','Friendly','A2','CloudSun','Crazy weather today, isn''t it? Have you been waiting long?',10),
('hobbies','Talking About Hobbies','Share what you do for fun.','You talk about free time with a new friend.','Friendly','A1','Guitar','So what do you like to do when you''re not working?',11),
('movies','Talking About Movies','Discuss films you like.','You discuss a film you both watched.','Casual','B1','Clapperboard','Have you seen anything good lately? I need a recommendation.',12),
('travel','Travel Conversation','Plan and describe a trip.','You talk to a travel agent about a holiday.','Professional','A2','Luggage','Hello! Where were you thinking of travelling to this year?',13),
('restaurant-complaint','Solving a Problem','Politely complain and resolve it.','Your order is wrong at a restaurant.','Professional','B2','AlertCircle','Good evening — is everything all right with your meal?',14);

INSERT INTO public.achievements (code, title, description, icon, metric, target, sort_order) VALUES
('first-lesson','First Lesson','Complete your very first lesson.','🏆','lessons_completed',1,0),
('ten-lessons','Getting Serious','Complete 10 lessons.','📘','lessons_completed',10,1),
('streak-3','Three in a Row','Keep a 3 day streak.','✨','streak',3,2),
('streak-7','7 Day Streak','Keep a 7 day streak.','🔥','streak',7,3),
('streak-30','Monthly Habit','Keep a 30 day streak.','🌟','streak',30,4),
('words-50','Word Collector','Learn 50 English words.','📚','words_learned',50,5),
('words-100','Vocabulary Builder','Learn 100 English words.','🧠','words_learned',100,6),
('words-1000','Vocabulary Master','Learn 1,000 English words.','👑','words_learned',1000,7),
('first-conversation','First Conversation','Finish your first AI conversation.','🎙️','conversations',1,8),
('ten-conversations','Real Talker','Finish 10 AI conversations.','💬','conversations',10,9),
('first-writing','First Writing','Submit your first writing exercise.','✍️','writings',1,10),
('xp-1000','Thousand Club','Earn 1,000 XP.','🚀','xp',1000,11);
